import type { GetServerSideProps, NextPage } from "next";
import { Session } from "next-auth/core/types";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { ReactElement } from "react";
import Center from "../pages/playlist/[playlistId]";
import Player from "../components/Player";
import Sidebar from "../components/Sidebar";

const Layout = ({ children }: { children: ReactElement }) => {
  return (
    <div className="bg-[#212328] h-screen overflow-hidden">
      <Head>
        <title>streamy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <Sidebar />
        {children}
      </main>

      <div className="sticky bottom-0">
        <Player />
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<{
  session: Session | null;
}> = async (context) => {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
};

export default Layout;
