import type { GetServerSideProps, NextPage } from "next";
import { Session } from "next-auth/core/types";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import { ReactElement } from "react";
import Player from "../components/Player";
import Sidebar from "../components/Sidebar";
import Image from "next/image";
import placeholderImg from "../placeholderImg";

const Layout = ({
  children,
}: {
  children: ReactElement[] | ReactElement | null;
}) => {
  const { data: session } = useSession();

  return (
    <div className="bg-grayfirst h-screen overflow-hidden">
      <Head>
        <title>streamy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <Sidebar />
        <section className="grow space-y-6">
          <header className="flex justify-end">
            <div
              className="flex items-center space-x-3
        opacity-90 hover:opacity-80 cursor-pointer rounded-full
        p-1 pr-2 bg-black text-white mr-2"
            >
              <Image
                className="rounded-full"
                src={session?.user?.image ?? placeholderImg}
                width={35}
                height={35}
                alt="user image"
              />
              <h2>{session?.user?.name}</h2>
            </div>
          </header>
          {children}
        </section>
      </main>

      <div className="sticky bottom-0">
        <Player />
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<{
  session: Session | null;
}> = async (context) => {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
};

export default Layout;
