import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <div className="bg-[#212328] h-screen overflow-hidden">
      <Head>
        <title>streamy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Sidebar />
        {/* center */}
      </main>

      <div>{/* player */}</div>
    </div>
  );
};

export default Home;
